[project]
name = "iqm-quantum-school"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "qrisp[iqm]>=0.7.17",
]
